In [2]:
import numpy as np
list_ = [ '1' , '2' ,'3' , '4' , '5' ]
array_list = np.array(object = list_)

# **Q1**

**Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.**

**Answer:**

Yes, there is a difference in the data types of the variables list_ and array_list. The variable list_ is a Python list, while array_list is a NumPy array.


In [3]:
type(list_)

list

In [4]:
type(array_list )

numpy.ndarray

# **Q2**

**Write a code to print the data type of each and every element of both the variables list_ and arra_list.**


**Answer:**


In [5]:
print("Data type of elements in list_:")
for element in list_:
    print(type(element))

print("Data type of elements in array_list:")
for element in array_list:
    print(type(element))

Data type of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Data type of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


# **Q3**

Considering the following changes in the variable, array_list:

    array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

    
**Answer:**


In [6]:
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

print("Data type of elements in list_:")
for element in list_:
    print(type(element))

print("Data type of elements in array_list:")
for element in array_list:
    print(type(element))

Data type of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Data type of elements in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


# **Q4**

Consider the below code to answer further questions:
import numpy as np

    num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
    num_array = np.array(object = num_list)

Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

**Answer:**



In [7]:
num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

In [8]:
print("Shape of num_array:", num_array.shape)

print("Size of num_array:", num_array.size)

Shape of num_array: (2, 3)
Size of num_array: 6



# **Q5**

**Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function**

**Answer:**


In [9]:
zeros_array = np.zeros((3, 3))
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# **Q6**

**Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]**

**Answer:**


In [10]:
identity_matrix = np.identity(5)

print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
